services:
  mysql-db:
    restart: always
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  eureka:
    restart: always
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
     mysql-db:
       condition: service_started
  config-server:
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - "8888:8888"
    volumes:
      - ./config-microservicios:/config-microservicios
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
  estudiantes-service:
    restart: always
    build:
      context: ./estudiantes-service
      dockerfile: Dockerfile
    container_name: estudiantes
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_estudiantes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  docentes-service:
    restart: always
    build:
      context: ./docentes-service
      dockerfile: Dockerfile
    container_name: docentes
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_docentes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  asignaturas-service:
    restart: always
    build:
      context: ./asignaturas-service
      dockerfile: Dockerfile
    container_name: asignaturas
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_asignaturas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  tutorias-service:
    restart: always
    build:
      context: ./tutorias-service
      dockerfile: Dockerfile
    container_name: tutorias
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_tutorias
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka
      - config-server
      - tutorias-service
      - asignaturas-service
      - docentes-service
      - estudiantes-service
      - mysql-db
volumes:
  mysql_data:


