server.port=8093

spring.application.name=asignaturas-service

spring.datasource.url=jdbc:mysql://localhost:3306/bd_asignaturas
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect